const HOTELS = [
    { n: 'Yalmakan', z: 'Zona Hotelera' }, { n: 'Westin Resort Cancun', z: 'Zona Hotelera' }, { n: 'Club Med', z: 'Zona Hotelera' }, { n: 'Solymar', z: 'Zona Hotelera' }, { n: 'Hotel NYX Cancun', z: 'Zona Hotelera' }, { n: 'GR Solaris', z: 'Zona Hotelera' }, { n: 'Hotel Krystal Cancun', z: 'Zona Hotelera' }, { n: 'Krystal Altitude Cancun', z: 'Zona Hotelera' }, { n: 'Moon Palace Nizuc', z: 'Zona Hotelera' }, { n: 'Moon Palace The Grand', z: 'Zona Hotelera' },
    { n: 'Jade', z: 'Zona Hotelera' }, { n: 'Iberostar Selection Cancun', z: 'Zona Hotelera' }, { n: 'Royal Solaris Cancun', z: 'Zona Hotelera' }, { n: 'Sun Palace', z: 'Zona Hotelera' }, { n: 'Now Emerald Cancun', z: 'Zona Hotelera' }, { n: 'Paradisus Cancun', z: 'Zona Hotelera' }, { n: 'Hotel Riu Cancun', z: 'Zona Hotelera' }, { n: 'Kempinski Hotel Cancun', z: 'Zona Hotelera' }, { n: 'Gran Oasis Cancun', z: 'Zona Hotelera' }, { n: 'Seadust Cancun Family Resort', z: 'Zona Hotelera' },
    { n: 'Moon Palace Sunrise', z: 'Zona Hotelera' }, { n: 'Hyatt Ziva Cancun', z: 'Zona Hotelera' }, { n: 'Fiesta Americana Coral Beach', z: 'Zona Hotelera' }, { n: 'Condominios Maralago', z: 'Zona Hotelera' }, { n: 'Fiesta Americana Villas Cancun', z: 'Zona Hotelera' }, { n: 'Hotel Riu Palace Las Americas', z: 'Zona Hotelera' }, { n: 'Melia Casa Maya', z: 'Zona Hotelera' }, { n: 'Hotel Riu Caribe', z: 'Zona Hotelera' }, { n: 'Melody Maker Cancun', z: 'Zona Hotelera' }, { n: 'The Westin Lagunamar', z: 'Zona Hotelera' },
    { n: 'Secrets The Vine Cancun', z: 'Zona Hotelera' }, { n: 'Golden Parnassus', z: 'Zona Hotelera' }, { n: 'The Royal Sands', z: 'Zona Hotelera' }, { n: 'Las Arenas Reales', z: 'Zona Hotelera' }, { n: 'Hotel Flamingo', z: 'Zona Hotelera' }, { n: 'Sunscape Resort', z: 'Zona Hotelera' }, { n: 'Le Blanc Spa Resort', z: 'Zona Hotelera' }, { n: 'Emporio Cancun', z: 'Zona Hotelera' }, { n: 'Iberostar Selection Coral Cancun', z: 'Zona Hotelera' }, { n: 'Hilton Cancun Mar Caribe All-Inclusive Resort', z: 'Zona Hotelera' },
    { n: 'The Royal Islander', z: 'Zona Hotelera' }, { n: 'Iberostar Cancun', z: 'Zona Hotelera' }, { n: 'Beachscape Kin Ha Villas & Suites', z: 'Zona Hotelera' }, { n: 'Hotel Fiesta Americana Condesa', z: 'Zona Hotelera' }, { n: 'JW Marriott Cancun Resort', z: 'Zona Hotelera' }, { n: 'Marriott Cancun Resort', z: 'Zona Hotelera' }, { n: 'Hotel Dos Playas Faranda', z: 'Zona Hotelera' }, { n: 'InterContinental Presidente Cancun Resort', z: 'Zona Hotelera' }, { n: 'Bell Air Cancun', z: 'Zona Hotelera' }, { n: 'Occidental Costa Cancun', z: 'Zona Hotelera' },
    { n: 'Sunset Royal Beach Resort', z: 'Zona Hotelera' }, { n: 'Live Aqua Beach Resort', z: 'Zona Hotelera' }, { n: 'Beach Palace', z: 'Zona Hotelera' }, { n: 'Aquamarina 1', z: 'Zona Hotelera' }, { n: 'Aquamarina 2', z: 'Zona Hotelera' }, { n: 'Aquamarina Reception', z: 'Zona Hotelera' }, { n: 'Grand Oasis Palm', z: 'Zona Hotelera' }, { n: 'Royal Resort The Royal Cancun', z: 'Zona Hotelera' }, { n: 'Dreams Vista Cancun Golf & Spa Resort', z: 'Zona Hotelera' }, { n: 'Hotel Riu Ventura', z: 'Zona Hotelera' },
    { n: 'Renaissance Cancun Resort & Marina', z: 'Zona Hotelera' }, { n: 'Hotel Riu Palace Peninsula', z: 'Zona Hotelera' }, { n: 'Hotel Riu Palace Kukulkan', z: 'Zona Hotelera' }, { n: 'Grand Park Royal Cancun Caribe', z: 'Zona Hotelera' }, { n: 'Temptation Resort Spa Cancun', z: 'Zona Hotelera' }, { n: 'Hyatt Zilara Cancun', z: 'Zona Hotelera' }, { n: 'Hard Rock Hotel Cancun', z: 'Zona Hotelera' }, { n: 'GR Caribe Deluxe By Solaris', z: 'Zona Hotelera' }, { n: 'Club Med Cancun', z: 'Zona Hotelera' }, { n: 'Omni Cancun Hotel & Villas', z: 'Zona Hotelera' },
    { n: 'Cancun Bay Resort', z: 'Zona Hotelera' }, { n: 'Calypso Hotel', z: 'Zona Hotelera' }, { n: 'Sotavento Yacht Club', z: 'Zona Hotelera' }, { n: 'Occidental Tucancun', z: 'Zona Hotelera' }, { n: 'Oleo Cancun Playa', z: 'Zona Hotelera' }, { n: 'Cancun Clipper Club', z: 'Zona Hotelera' }, { n: 'Club Regina Cancun', z: 'Zona Hotelera' }, { n: 'Selina Hotel Cancun Lagoon Zona Hotelera', z: 'Zona Hotelera' }, { n: 'GR Solaris Cancun', z: 'Zona Hotelera' }, { n: 'SLS Cancun Hotel & Residences', z: 'Zona Hotelera' },
    { n: 'Hotel Grand Royal Lagoon', z: 'Zona Hotelera' }, { n: 'Jade Reception', z: 'Zona Hotelera' }, { n: 'Condo Hotel Las Gaviotas', z: 'Zona Hotelera' }, { n: 'Sina Suites Cancun', z: 'Zona Hotelera' }, { n: 'La Villa du Golf a Cancun', z: 'Zona Hotelera' },
    { n: 'Comfort Inn Cancun', z: 'Centro' }, { n: 'Hampton Inn', z: 'Centro' }, { n: 'La Quinta by Wyndham Cancun', z: 'Centro' }, { n: 'Hacienda de Castilla', z: 'Centro' }, { n: 'Ambiance Suites Cancun', z: 'Centro' }, { n: 'Hotel Plaza Caribe', z: 'Centro' }, { n: 'Aloft', z: 'Centro' }, { n: 'Krystal Urban Cancun & Beach Club', z: 'Centro' }, { n: 'Cancun International Suites', z: 'Centro' }, { n: 'Hotel Maya Caribe', z: 'Centro' },
    { n: 'Hotel Imperial Laguna', z: 'Centro' }, { n: 'Ramada', z: 'Centro' }, { n: 'Hotel Xbalamque', z: 'Centro' }, { n: 'Ibis Cancun Centro', z: 'Centro' }, { n: 'Hotel Batab', z: 'Centro' }, { n: 'Las Palmas', z: 'Centro' }, { n: 'Mi Hotel', z: 'Centro' }, { n: 'Alux', z: 'Centro' }, { n: 'Hostel Natura', z: 'Centro' }, { n: 'Hotel Colonial San Carlos', z: 'Centro' },
    { n: 'Hotel Green 16', z: 'Centro' }, { n: 'Hotel Tankah', z: 'Centro' }, { n: 'Hacienda Hotel', z: 'Centro' }, { n: 'VIP Loungue Casa Nueva', z: 'Centro' }, { n: 'VIP Loungue Casa Grande', z: 'Centro' }, { n: 'Le Monde', z: 'Centro' }, { n: 'Hotel Carrillo\'s', z: 'Centro' }, { n: 'Hotel Villas Mira Sol', z: 'Centro' }, { n: 'Hotel Ceresas', z: 'Centro' }, { n: 'Hotel Jardin', z: 'Centro' },
    { n: 'Hotel Uxmal', z: 'Centro' }, { n: 'Fiesta Inn Cancun Las Americas', z: 'Centro' }, { n: 'Hostal Bambu', z: 'Centro' }, { n: 'Nomads Hotel Hostel & Bar', z: 'Centro' }, { n: 'GAMMA Cancun Centro', z: 'Centro' }, { n: 'Hotel Mexico', z: 'Centro' }, { n: 'Azteca', z: 'Centro' }, { n: 'Casa Kosan', z: 'Centro' }, { n: 'Casa Palmera by B&G', z: 'Centro' }, { n: 'Casa Namal', z: 'Centro' },
    { n: 'The Yellow Capsule', z: 'Centro' }, { n: 'Hilton Garden Inn', z: 'Centro' }, { n: 'Hive Cancun', z: 'Centro' }, { n: 'Soberanis', z: 'Centro' }, { n: 'Mura Hotel Boutique', z: 'Centro' }, { n: 'Hotel Luma', z: 'Centro' }, { n: '1st Luxury Warehouse', z: 'Centro' }, { n: 'Hotel Villa Leo', z: 'Centro' }, { n: 'Mex Hoteles Cancun', z: 'Centro' }, { n: 'Mayafair Design Hotel', z: 'Centro' },
    { n: 'Hotel Kavia', z: 'Centro' }, { n: 'Hotel Adhara', z: 'Centro' }, { n: 'Nomads Party Hostel', z: 'Centro' }, { n: 'Selina Hostel Cancun', z: 'Centro' }, { n: 'Tulipanes Cancun', z: 'Centro' }, { n: 'Villa Palmeras', z: 'Centro' }, { n: 'Hotel Adhara Express', z: 'Centro' }, { n: 'Eco-Hotel El Rey del Caribe', z: 'Centro' },
    { n: 'Fairfield Inn & Suites Cancun Airport', z: 'Aeropuerto' }, { n: 'City Express Plus by Marriott Cancun Aeropuerto Riviera', z: 'Aeropuerto' }, { n: 'Avani Cancun Airport Hotel', z: 'Aeropuerto' }, { n: 'Marriott Courtyard Cancun Airport', z: 'Aeropuerto' }
];
